AWSTemplateFormatVersion: '2010-09-09'
Description: Infraestructura para ETL de riesgo y penalizaciones

Resources:
  DataBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: etl-riesgo-penalizaciones-data

  ETLLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /etl/riesgo-penalizaciones
      RetentionInDays: 7

  ETLExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: ETLExecutionRole
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: [ec2.amazonaws.com]
            Action: sts:AssumeRole
      Policies:
        - PolicyName: ETLS3Access
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - s3:PutObject
                  - s3:GetObject
                Resource: "arn:aws:s3:::etl-riesgo-penalizaciones-data/*"
              - Effect: Allow
                Action:
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: "*"
