AWSTemplateFormatVersion: '2010-09-09'
Description: Infraestructura para ETL de riesgo de penalizaciones desde MongoDB

Resources:

  ETLRiskDataBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: etl-riesgo-penalizaciones-data
      VersioningConfiguration:
        Status: Enabled

  ETLRiskLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /etl/riesgo-penalizaciones
      RetentionInDays: 14

  EC2ETLExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: EC2_ETL_RiskRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
        - arn:aws:iam::aws:policy/CloudWatchLogsFullAccess

Outputs:
  S3BucketName:
    Description: Nombre del bucket de datos
    Value: !Ref ETLRiskDataBucket

  LogGroupName:
    Description: Grupo de logs para seguimiento
    Value: !Ref ETLRiskLogGroup

  EC2RoleName:
    Description: Rol IAM que puede usar EC2
    Value: !Ref EC2ETLExecutionRole